package com.dingmouren.greendao;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.dingmouren.dingdingmusic.bean.LocalMusicBean;

import com.dingmouren.greendao.LocalMusicBeanDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig localMusicBeanDaoConfig;

    private final LocalMusicBeanDao localMusicBeanDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        localMusicBeanDaoConfig = daoConfigMap.get(LocalMusicBeanDao.class).clone();
        localMusicBeanDaoConfig.initIdentityScope(type);

        localMusicBeanDao = new LocalMusicBeanDao(localMusicBeanDaoConfig, this);

        registerDao(LocalMusicBean.class, localMusicBeanDao);
    }
    
    public void clear() {
        localMusicBeanDaoConfig.clearIdentityScope();
    }

    public LocalMusicBeanDao getLocalMusicBeanDao() {
        return localMusicBeanDao;
    }

}
