package com.dingmouren.greendao;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.dingmouren.dingdingmusic.bean.MusicBean;

import com.dingmouren.greendao.MusicBeanDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig musicBeanDaoConfig;

    private final MusicBeanDao musicBeanDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        musicBeanDaoConfig = daoConfigMap.get(MusicBeanDao.class).clone();
        musicBeanDaoConfig.initIdentityScope(type);

        musicBeanDao = new MusicBeanDao(musicBeanDaoConfig, this);

        registerDao(MusicBean.class, musicBeanDao);
    }
    
    public void clear() {
        musicBeanDaoConfig.clearIdentityScope();
    }

    public MusicBeanDao getMusicBeanDao() {
        return musicBeanDao;
    }

}
